### ISSUE TITLE
Aktuální stránka se neresetuje při změně parametrů filtrace

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#119]
Pokud použiji listování, tak po změně parametrů vyhledávání/filtrace by mělo automaticky dojít k návratu na první list. Stávající stav je extrémně matoucí.

**Comment by pbartosova** [comment]
Reprodukováno. Na opravě budeme pracovat.

**Comment by pbartosova** [comment]
Snad se jedná o menší zásah. Odhad 1 den.
