### ISSUE TITLE
Aktualizace externich knihoven

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#12]
Chyba při pokusu o reindex. Vyčištění proběhlo dobře, ale nechce indexovat. Nevím, zda nesouvisí s předchozí chybou (login procedura). Chybová hláška:

{"message": {
  "clean": {"message": "Index cleaned"},
  "full": {"error": "java.lang.IllegalStateException: Connection pool shut down"}
}}

**Comment by albertoh** [comment]
Uz bezi.

Souvisi to s bugem v apache knihovne.

https://stackoverflow.com/questions/25889925/apache-poolinghttpclientconnectionmanager-throwing-illegal-state-exception

Meli bychom aktualizovat vsechny knihovny

**Comment by motyc** [comment]
To bude tedy asi na @MichalKminek

**Comment by albertoh** [comment]
Ne ne, jsou externi knihovny, ktere pouziva aplikace.
Akorat neudelam to rychle bez testovani.

**Comment by motyc** [comment]
Ok, chápu. Tak to prosím veďme v patrnosti. Díky

**Comment by albertoh** [comment]
Bude s testovacim serverem
