### ISSUE TITLE
Persistentní odkazy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#123]
Po zadání adresy https://digiarchiv.aiscr.cz/id/C-TX-194704015 dojde k otevření Digiarchivu, ale někdy se nenačte odpovídající dokument. To se stane až po refreshi stránky. Někdy dokument jen problikne a zase zmizí. Je to takové zvláštní - nemůže to nějak souviset s úpravou #59?

Děje se to jen při přímém zadání odkazu nebo kliknutí na něj mimo Digiarchiv. Pokud použiji tlačítko persistentního odkazu v Digiarchivu, otevře se stránka rovnou správně.

**Comment by pbartosova** [comment]
Prověříme to. S #59  by to nemělo souviset, ale je nutné to detailněji ověřit. Momentálně má ale prioritu dořešit issue #120.

**Comment by motyc** [comment]
Zdá se, že nyní funguje ok. Budu dále sledovat, ale prozatím zavírám.

**Comment by motyc** [comment]
Tak se to děje stále, ale zdá se, že jen s některými dokumenty. Nevím, v čem leží klíč. Momentálně je to třeba https://digiarchiv.aiscr.cz/id/M-TX-201000747

Někdy se po refreshi načte, někdy ne. Je to velice zvláštní.

**Comment by motyc** [comment]
Mám to reportováno i od jiných uživatelů.

**Comment by motyc** [comment]
Budeme řešit až v novém Digiarchivu.
