### ISSUE TITLE
Optimalizovat předávání dat mezi AMČR a Digiarchivem

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#125]
Jde zejména o úpravu exportní procedury tak, aby se nepředávala pro Digiarchiv zbytná data (nearchivované dokumenty, PIAN bez vazeb atd.).

**Comment by pbartosova** [comment]
Opět ideálně provést s úpravami na api, pak odhad méně než 1MD

**Comment by pbartosova** [comment]
Nejlépe si hned na začátku definovat úpravy, abychom je provedli najednou.

**Comment by motyc** [comment]
Zde shrnuji podmínky indexace pro jednotlivé DT. Hierarchicky přímo podřízené DT jsou indexovány vždy ve vztahu k nadřazené DT (jsou jmenovány pouze výčtem u příslušné DT). Zmiňuji i stav plánovaný do budoucna po implementaci vyhledávání z AMČR na úrovni všech prvků:

1) Dokumenty (Extra data, Jednotky dokumentu, Komponenty dokumentu, Nálezy dokumentu, Neidentifikované akce, Tvary, Lety)
- stav = 3
- rada <> ZA AND rada <> ZL

2) Soubory
- pokud je vazba na indexovaný Dokument nebo Samostatný nález

3) Projekty
- neindexujeme
- (v budoucnu indexovat, pokud je vazba na indexovanou Akci)

4) Akce (Dokumentační jednotky, Komponenty, Nálezy, PIAN, ADB)
- pokud je vazba na indexovaný dokument (v budoucnu vše bez ohledu na vazby)
- stav = 4 OR stav = 5 OR stav = 8

5) Lokality (Dokumentační jednotky, Komponenty, Nálezy, PIAN)
- pokud je vazba na indexovaný dokument (v budoucnu bez ohledu na vazby)
- stav = 3

6) Externí zdroje (Externí odkazy)
- pokud je vazba na indexovanou akci/lokalitu (v budoucnu bez ohledu na vazby) 

7) Samostatné nálezy
- stav = 4

**Comment by pbartosova** [comment]
Teď trochu nerozumím požadavkům, 
1. Podle prvního popisu se měly upravovat csv exporty. A to se napr. u 4 dost komplikuje. Šlo by to, ale bude to složitější.
2. Co je ale podle mně problém, je že internalApi pro digitální archiv používá stejný SELECT jako smart_export, který používá pro exporty administrátor.
Pokud by měl administrátor dostávat vše, musel by se export pro DigiArchiv uplně oddělit.

**Comment by motyc** [comment]
Nevěděl jsem, že je to tolik svázané s ručním exportem. Je příliš pracné to API v tomto smyslu rozdělit, abychom nemuseli dělat zbytečné kompromisy?

Navrhuji si ohledně této věci zavolat a dořešit to na začátku ledna společně s dalšími otázkami, co jsou již nastole v jiných issues. V případě potřeby se lze bavit i o nějakém doplatku.

**Comment by pbartosova** [comment]
Jsme pro to rozdělit. Podívám se na to, jak by to šlo udělat.
