### ISSUE TITLE
Náhledy se generují jen černobíle

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#128]
Patrně souvisí s opravou #77, nicméně náhledy se i u barevných PDF nyní generují jen ve stupních šedi.

Příklad: https://digiarchiv.aiscr.cz/id/C-TX-195007083

**Comment by pbartosova** [comment]
Co bývá obsahem pdf? Dokumenty s převahou textu nebo i fotografie?

**Comment by motyc** [comment]
Existuje naprosto nepřeberné množství variant. Jsou dokumenty, kde jde hlavně o text (tištěný i psaný v ruce), jiné jsou zas čistě fotografické, jinde jde o kombinaci. Mohou tam být plány, mapy, vpisky tužkou i pastelkami. Drobné kresby, skeny pauzák... Prostě naprosto rozmanitý archivní materiál.

**Comment by motyc** [comment]
Ještě doplňuji, že před tou opravou byly barevné náhledy bez problémů, chyba se týkala černobílých.

**Comment by pbartosova** [comment]
Stále probíhá testování a nic nefunguje. Odhad max 3dny.

**Comment by albertoh** [comment]
Nasel jsem zmenu v kodu, ktera zpusobila generovani cernobilych obrazku. Tato zmena by mela rozslisit cernobile a barevni obrazky. Bohuzel casto bere vsechno jako cernobile.
 Abych mohl spravne opravit chovani, potreboval bych priklad cernobileho pdf, pro ktere se pred opravou generovalo nekvalitny nahled. V comment k issue #77 #issuecomment-503080771 je uveden dokument https://digiarchiv.aiscr.cz/id/C-TX-192000023. 
Pro testovani obrazku pouzivam  http://digiarchiv.amapa.cz/id/M-FT-110598800 
Jsou dalsi pdf, s kterymi byly problemy? Prosim o zaslani, at muzu to vsechno poradne testovat.

**Comment by motyc** [comment]
Vzhledem k tomu, že dosud se data kvůli problému s barvami negenerovala znovu, celkem snadno takové případy najdeš sám v aktuálních datech na produkci. Je to v podstatě generální problém pro vše, kde náhledy vznikly před červencem loňského roku.
Velice názorný je ale třeba tento příklad: https://digiarchiv.aiscr.cz/id/C-TX-193700411
Projevovalo se to ale na většině dokumentů (černobílé či šedostupňové).

![image](https://user-images.githubusercontent.com/20186892/80581759-ec300780-8a0d-11ea-95b5-ec8c826a4493.png)

**Comment by albertoh** [comment]
Uvedeny priklad se mi ted generuje takto:
![0](https://user-images.githubusercontent.com/5946836/80602570-98ceb100-8a2f-11ea-8368-b03c16a2a307.jpg)

Potreboval bych spustit generovani vsech nahledu na testu, abych mohl videt vysledky tamnich obrazku. Muzu?

**Comment by motyc** [comment]
To je bezvadné!

Ohledně spuštění generování - obávám se, že jsme to negenerovali kvůli místu na test serveru. Bude třeba, aby se vyjádřil @MichalKminek. Asi mu raději prosím napiš či zavolej.

**Comment by albertoh** [comment]
Na testu uz byly vygenerovane nekolik nahledu. Nemalo. Regeneroval jsem je (to nezabral dalsi misto na disku, vidim tam 10GB volnych).
Ted prochazim vysledky.

**Comment by albertoh** [comment]
Dobry priklad pro zrovnani vysledku je dokument M-TX-201200345:
https://digiarchiv-test.aiscr.cz/id/M-TX-201200345
https://digiarchiv.aiscr.cz/id/M-TX-201200345

Tento pdf ma text, cernobile obrazky a barevne.
Na testu ale pres rozhrani ma jenom jednu stranku. Je to zpusobeno testovacimi datami v tabulce "soubor". Muzeme prochazet vsechny nahledy stranek primo pres servlet:

https://digiarchiv-test.aiscr.cz/pdf?size=medium&id=1496238832823_MTX201200345.pdf&page=79
https://digiarchiv.aiscr.cz/pdf?size=medium&id=1496303690473_MTX201200345.pdf&page=79

Ted jeste musim doresit problem spravne detekce TIFF (a asi i PNG). Stava se, ze barevny obrazek muze mit informaci o barvach enkodovanou v palette, a to pusobi nespravnou detekci hloubky pixelu.

**Comment by MichalKminek** [comment]
V pripade potreby muzeme i na testu pridavat misto, prozatim tedy neni 
potrebne.

Dne 30.04.2020 v 11:28 Alberto Hernandez napsal(a):

**Comment by albertoh** [comment]
Regeneroval jsem nahledy na testovacim serveru. Prosim o kontrolu vysledku

**Comment by motyc** [comment]
Musel jsem to celé promáznout, protože se v tom vůbec nedalo vyznat, co je starý náhled a co nový. Počkám, až se to opět vygeneruje jako celek a potvrdím.

**Comment by albertoh** [comment]
Mam pustit proces generovani nahledu?

**Comment by motyc** [comment]
Ještě se to stále maže. Je tam toho spousta. Navíc se mi podle logu zdálo, že se to pouští samo každou hodinu (podobně jako na produkci), takže by to nemělo být potřeba.

**Comment by motyc** [comment]
Co jsem zatím prošel, tak vypadá dobře. Ještě to prokontroluji, ale myslím, že to můžeme považovat za vyřešené. Bohužel se to ale ukáže hlavně až na produkčních datech.

**Comment by motyc** [comment]
Tak nasazení na produkci bohužel ukazuje, že se to úplně vyřešit nepodařilo. Např. tento dokument se i nyní vygeneroval ve stupních šedi, přestože je barevný: https://digiarchiv.aiscr.cz/id/C-TX-201202784

**Comment by motyc** [comment]
Další příklad: https://digiarchiv.aiscr.cz/id/C-TX-192601320

**Comment by albertoh** [comment]
Vidim stary jar soubor na serveru (20.6.2019). Asi toto nebylo nasazeno.
Musi se buildovat novy jar, zkopirovat na server a regenerovat nahledy

**Comment by motyc** [comment]
@albertoh A můžeš to tam prosím dát? Hrozí ještě někde, že se to nasadilo neúplné? Je trošku škoda, že od pátku generujeme nové náhledy úplně zbytečně... Ach jo (vím, že to není na Tvé straně). Příště bys měl asi raději nasazovat Ty, nebo to musí být v koordinaci.

**Comment by albertoh** [comment]
Procistil jsem thumbs/
Nasadil novy jar. Uz to bezi.
Kontroloval jsem ty dva dokumenty, a byly OK. Ted tam nejsou, jeste nedobehlo.

**Comment by motyc** [comment]
Skvěle, děkuji. Nechám issue otevřené a zavřu jej, až toho bude více a půjde to snadněji kontrolovat. Spustím teď reindex, Ať se správně nastaví dokumenty bez náhledů.
