### ISSUE TITLE
Tooltip s nápovědou u vyhledávacího pole

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#129]
K hlavnímu vyhledávacímu poli doplnit tooltip s jednoduchou nápovědou:

`Při zadávání víceslovných výrazů použijte uvozovky (např. "hledaný výraz" či "hledaný-výraz"). V opačném případě dojde k vyhledání všech výskytů dílčích užitých slov samostatně.`

`Use quotation marks when entering multi-word terms (such as "search term" or "search-term"). Otherwise, all occurrences of specific used words are searched separately.`

**Comment by pbartosova** [comment]
Raději later. asi není stěžejní funkcionalita.

**Comment by motyc** [comment]
Toto bych preferoval udělat brzy, pokud to není komplikované. Opakovaně se uživatelé zmateně dotazují, že jim vyhledávání zdánlivě nefunguje. Lze navrhnout i jiné řešení, kam informaci dát, pokud je tento návrh příliš komplikovaný. Třeba nějak graficky přijatelně zakomponovat pod vyhledávací pole.

**Comment by pbartosova** [comment]
Odhad max. 2h.

**Comment by pbartosova** [comment]
Text je na tooltip dlouhý. Okno se textu přizpůsobuje, ale nepočítá se tak s dlouhým textem. Chtělo by to pro tento případ zadat pevnou délku, to se ale nepodařilo. Zkoušeli jsme to různě, ale nikdy se to finálně neprojeví.

**Comment by motyc** [comment]
A co tam je podle Vás špatně? Mně to přijde dobré, a to ve všech prohlížečích, co mám (Chrome, Mozilla, Explorer, Edge).

Jediný problém je, že tam jsou v nápovědě použity špatné uvozovky (má být `&ldquo;` nikoli `&lsquo;`).

**Comment by pbartosova** [comment]
Líbilo by se nám ,kdyby ten tooltip  měl větší šírku a text by tak vyšel jen třeba na tři řádky.
Text je dělaný pomocí překladu jako ostatní podobné položky. A tam by neměly být ty zmíněné uvozovky, protože do těch uvozovek se dává ten překlad.

**Comment by motyc** [comment]
Rozumím, asi by to vypadalo lépe, ale nepřijde mi, že by to teď vypadalo nějak hrozně. Zatím to stačí a třeba se na novém Angularu najde lepší řešení.
Ad uvozovky - no, proto také píšu "&ldquo;" a "&rdquo;" jako zástupné znaky, ale ne vlastní " (možná ale toto řešení nestačí, pak je třeba najít jiné, lepší). Problém je, že s jednoduchou uvozovkou to neplní účel a vyhledávají se slova i nadále odděleně, takže nápověda je zavádějící/chybná.

**Comment by pbartosova** [comment]
Na ty uvozovky asi nebude stačit úprava v json.
Nutno využít reg výrazy.

**Comment by motyc** [comment]
@albertoh zde je to hotové, ale musí se vyřešit ten problém s uvozovkami (viz výše)

**Comment by albertoh** [comment]
Prosim o kontrolu, zda tak si to predstavujete

**Comment by motyc** [comment]
Ano, perfektní.
