### ISSUE TITLE
Obsah jednotlivých polí je prázdný

### ISSUE THREAD

**Issue by pbartosova** [ARUP-CAS/aiscr-digiarchiv#130]
Zjistit, jaká je souvislost této chyby s https://github.com/ARUP-CAS/aiscr-amcr/issues/73, s novým releasem a aktualizací serveru.

**Comment by motyc** [comment]
Jaká pole máte konkrétně prosím na mysli?

**Comment by motyc** [comment]
Patrně neběží SOLR, řešíme.

**Comment by pbartosova** [comment]
Zatím funguje jen produkce.

**Comment by motyc** [comment]
Ještě doplňuji označení druhého identifikovaného problému ve facetách:
![image](https://user-images.githubusercontent.com/20186892/66500214-73914a00-eac1-11e9-81f2-5dac360a9754.png)

**Comment by pbartosova** [comment]
Dnes ještě provedena revize všech konfiguračních souboru solr, proveden restart tomcat a solr.
Problém ve facetách by mohly způsobovat data, jedná se totiž jen o dva dokumenty, ověřím, popř. doplním, co jim chybí.

**Comment by motyc** [comment]
O problém v datech po mém soudu nejde. Data jsou v pořádku a když kliknete na "+" tak tam jsou správná hesla. Problém je, že systém neví, kam je má zařadit a to muselo být někde v konfiguraci. Navíc určitě není problém dat, že tam chybí ta faceta s přístupností.

**Comment by pbartosova** [comment]
Opravena přístupnost.
Faceta je stejný problém jako #45 .
Prosím o spolupráci:
Posledně jste konfiguraci opravoval vy, můžete se prosím podívat na produkci do konfigurace, kam jste změnu evidoval, zda je v "kategoriet" nastaveno "foto události" a "kresba .." ? Tyto kategorie jsem musela přidat. Změna ale nezabrala. A to bohužel ani na testu při restartu solr, tomcatu a reindexaci.

**Comment by motyc** [comment]
Snad vyřešeno, není mi ale jasné, zda jsem to svým zásahem opravil já, nebo zda jste tam ještě něco od pátku dělala?
