### ISSUE TITLE
Prohledávají se i nezobrazovaná pole

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#132]
Pokud použiji pole pro vyhledávání, systém vrací dokumenty i na základě hodnot, které se vůbec nemají indexovat. Příkladem je dokument "C-TX-201900043", který se najde i na heslo Hasil. To se však  nachází pouze v emailu uživatele, který dokument vložil do systému, což je pole, které v Digiarchivu nezobrazujeme. Je třeba uvést to do souladu tak, aby se prohledávaly opravdu jen položky v Digiarchivu přímo zobrazované (takto je to extrémně matoucí pro uživatele).

**Comment by pbartosova** [comment]
S touto situací asi návrh nepočítal. Zkusím se podívat, jak to zaimplementovat přímo do searchapp. Odhad max 2dny.

**Comment by motyc** [comment]
Vyřeší se v rámci upgrade na nový Digiarchiv.
