### ISSUE TITLE
Doplnit do patičky informaci o aktuální verzi

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#133]
Podobně jako v AMČR (rozlišit produkci a test).

**Comment by pbartosova** [comment]
Tady trochu nechápu smysl, když rozdíl je vlastně vidět přímo v IP adrese, zda se jedná o test nebo produkci. Nebo vám jde o to,aby  měl každý svou číselnou řadu.

**Comment by motyc** [comment]
Hmhm, to máte pravdu. Asi v tomto případě stačí jedna řada...

**Comment by pbartosova** [comment]
Pokusíme se to udělat tak, aby se doplnilo automaticky při deploy, odhad 6h.

**Comment by pbartosova** [comment]
![image](https://user-images.githubusercontent.com/17924714/71253233-9e9ce300-2327-11ea-9d56-2c0134cf7a3a.png)

S jakou verzí chceme začít? A na kolik míst?

**Comment by motyc** [comment]
Budeme to držet standardně jako zde v releasech (https://github.com/ARUP-CAS/aiscr-digiarchiv/releases). Prosím, nezapomínejte je vytvářet při nasazování nových verzí. To platí pro i pro ostatní aplikace, které máme zde na GitHub. Měli bychom to dělat všude stejně.

**Comment by motyc** [comment]
S verzemi na testu pracujme stejně, jako to děláme v AMČR. Tj. ve čtvrtém řádu původního release. Bude to opět jednodušší kvůli ladění. Jsou takto vždy popsány i milestones, tak se tím jde řídit.

**Comment by pbartosova** [comment]
Ok, první verze na produkci bude 1.1.0.
