### ISSUE TITLE
Vyřešit správné zobrazení externích prolinků

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#137]
Např. Facebook bohužel k URL přidává sledovací kód, který Digiarchiv mylně chápe jako filtr. Je třeba to ošetřit tak, aby do filtrace pojímal jen "naše" parametry a nikoli neznámé, externě doplněné.

Příklad: https://digiarchiv.aiscr.cz/results?adv=heslar;komponenta_areal;and;hradi%C5%A1t%C4%9B;starts;hradi%C5%A1t%C4%9B&fbclid=IwAR32OStNZlf4qWIWu-6rw4pwOFuDow3Fq3t1YuMD6XLr_CCfCgIi3RbNneY

**Comment by albertoh** [comment]
Pridano do konfigurace seznam platnych parametru.
Mozno testovat na testu

**Comment by motyc** [comment]
Na testu je to perfektní. Lze to tedy nasadit s úpravou pro detektory
