### ISSUE TITLE
Nastavení překladů pro samostatné nálezy

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#138]
Prosím o zaslání aktuálních klíčů pro překlady GUI, udělám revizi.

**Comment by albertoh** [comment]
Ve slozce pro preklady (/var/lib/archeo/amcr/thesauri) neni zadny soubor pro samostatne dokumenty ("pas").
 Preklady nazvu pole v konfiguraci:
  "Pocet": "Počet" , "Number",
  "nalezove_okolnosti": "Okolnosti", "Circumstances"
  "hloubka": "Hloubka", "Deep"
  "poznamka": "Poznámka", "Note"
  "lokalizace": "Lokalizace", "Site"
  "Uložení nálezů": "Uložení nálezů", "Depository"
  "Ev. č": "Ev. č", "Id. num"

**Comment by motyc** [comment]
Tam ostatně ani být nemají, součásti UI dáváme přímo do konfigurace, ale možná bychom to časem bokem vystrčit mohli (už jen kvůli přehlednosti). Zde úprava:

"Pocet": "Počet" , "Count",
"nalezove_okolnosti": "Nálezové okolnosti", "Finding context"
"hloubka": "Hloubka", "Depth"
"poznamka": "Poznámka", "Note"
"lokalizace": "Lokalizace", "Location"
"Uložení nálezů": "Uložení nálezů", "Finds repository"
"Ev. č": "Ev. č", "Ev. no."

**Comment by motyc** [comment]
Podle mne je špatný klíč u uložení nálezů, které se tak vůbec nepřekládá.
Chybí taky některé klíče (nevím, jestli je mám dobře - beru z GUI):
"Nález": "Nález", "Find"
"Popis nálezu": "Popis nálezu", "Find description"

Zároveň se z nějakého důvodu nepřekládají hesláře.

**Comment by albertoh** [comment]
Opraveno

**Comment by motyc** [comment]
Stále se nepřekládá to uložení:
![image](https://user-images.githubusercontent.com/20186892/78129969-be5ca080-7418-11ea-800e-08ccb87e542c.png)

**Comment by albertoh** [comment]
Nevsiml jsem si. Uz je tam

**Comment by motyc** [comment]
Ty čteš vždycky půlku věty :) Ještě prosím ten okres a bude to.

**Comment by albertoh** [comment]
Ach jo! Promin. Uz je tam

**Comment by motyc** [comment]
V pořádku :)
