### ISSUE TITLE
Lze filtrovat a vyhledávat podle nepřístupných dat

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#142]

**Comment by albertoh** [comment]
Potreboval bych priklady. Toto chovani se tyka jen novych dokumentu samostatnych nalezu?

**Comment by motyc** [comment]
Jde o to, že např. katastr, i když je v datech skrytý, tak se zobrazí ve filtraci a filtrace podle něj funguje. Podobně i přes vyhledávání jej lez najít. Netestoval jsem to důsledně u jiných položek, ale asi to bude stejné. Je pravda, že to trošku souvisí asi i s issue #132 

Příklady zde:

![image](https://user-images.githubusercontent.com/20186892/77748728-1b271800-7021-11ea-8fcc-c7d489c4e07d.png)

![image](https://user-images.githubusercontent.com/20186892/77748812-4578d580-7021-11ea-8c30-66ad330b6f2a.png)

**Comment by albertoh** [comment]
Katastr a lokalizace jsou zvlastni pripady pro samostatne nalezy. Podle zadani se maji zobrazovat jen pokud uzivatel ma dostatecna opravneni.
 Abychom dosahli vylouceni z vysledku budeme potrebovat zmenit index a indexer tak, aby fulltextove hledani neprobihalo v jednom poli, ale vytvorit fulltextove pole pro kazdou urovni pristupnosti, a dotazovat index s ohledem na prava prihlaseneho uzivateli.

**Comment by motyc** [comment]
Rozumím, nic jiného asi nezbude. Ono se nám tento přístup s oddělenými indexy tak jako tak do budoucna bude hodit.

**Comment by albertoh** [comment]
Nez zacnu na tom pracovat chtel bych ujasnit, jestli pole pro samostatne nalezy a ostatni dokumenty maji rozdilne chovani. Tj, katastr a lokalizace pro ostatni dokumenty se zobrazujou vzdy stejne, pro vsechny uzivatele, je to spravne?.  Budou i dalsi takova pole?

**Comment by motyc** [comment]
Ono je asi třeba popsat si to chování ve vztahu k přístupnosti celkově:
- Dokumenty - přístupnost ovlivňuje pouze možnost zobrazit soubor
- Akce a lokality - přístupnost ovlivňuje zobrazení celého záznamu (vidím/nevidím)
- Samostatné nálezy - přístupnost ovlivňuje zobrazení lokalizací

Tj. už nyní pracujeme se třemi různými variantami. Nejjednodušší (i pro budoucnost) bude chápat samostatné nálezy nikoli jako typ dokumentu, ale jako zcela odlišný typ záznamu, u kterého se snažíme sjednotit chování v rámci existujícího zobrazení a vyhledávání přes GUI.

Abych ale odpověděl přesně na otázku u dokumentů je správně chování, že se katastr a lokalizace zobrazuje v případě, že jsou přístupné entity, ve kterých jsou tato data uložená (akce, lokalita, neident. akce). U samostaných nálezů je princip jiný.

Do budoucna to zatím predikovat nedokážu, ale budeme se snažit spíše se držet co nejméně variant řešení. Snad to je takto popsáno srozumitelně, případně se prosím doptej.

**Comment by motyc** [comment]
Už se mi to zdá být správně pro fulltext, ale:
- ve facetách stále vidím i skryté katastry
- v rozšířeném dotazu katastr najdu (přes všechna pole i katastr)

Patrně to bude obdobné pro jiná skrytá pole.

**Comment by albertoh** [comment]
Moje oprava byla v pridani rozdilne textove poli do indexu pro fulltextove hledani. Jedno pro prihlasene a jedno bez prihlaseni. Ale index zustal jenom jeden. To znamena, ze dokumenty maji v indexu udaje o lokalizace a katastr, ale pri fulltextove hledani nenajdeme pokud nejsme prihlasene. Pri jinem typu hledani muzeme najit, ale udaje jsou skryte. Ale ve facetech zustanou, protoze solr vraci vsechny, a my nemuzeme tam rozlisovat, jestli udaj, rekneme okres, je tam "opravnene", tj, existuje dokument s dannim katastrem a pristupnosti "A", nebo nikoli. Abychom dosahli pozadanou funcionalitu, meli bychom mit dva indexy kompletne. To je docela velky zasah do indexeru a rozhrani.
Podobny scenar plati pro rozsirenem vyhledavani. Ale neuplne. Aktualne seznam hodnot v dropdown prichazi z heslare. A ten ma vsechny hodnoty. Pred hledanim nemuzeme nic excludovat. A po hledani muzeme, ale jen pokud zmenime zdroj: ne z heslare, ale z jiz vracenych facet. Toto je taky velka zmena v kodu.
 Vsechno je mozne, ale neni to mala oprava. Samostatne nalezy meni celou stavajici logiku.

**Comment by motyc** [comment]
Rozumím a díky za vysvětlení. Jako jediné možné řešení teď vidím do filtrace a rozšířeného vyhledávání vůbec neindexovat u samostatných nálezů pole katastr a lokalizace (tj. tyto funkce nebudou pro sam. nálezy dostupné). Zároveň necháme issue otevřené a je třeba to vyřešit při plánovaném updatu Digiarchivu.

**Comment by albertoh** [comment]
Kdyz pises neindexovat, znamena i ne zobrazovat pro nikoho?
Kdyz nebudeme vubec indexovat, pri filtrace podle lokalizace / katastr zadne samostatny nalez se nenajde

**Comment by motyc** [comment]
Pardon za nepřesnou terminologii, nevím, jak tomu říkat. Myslel jsem nepoužívat/nezobrazovat ve facetě filtrace a v rozšířeném vyhledávání. Tam předpokládám je nějaké mapování, které by šlo zrušit, ne? Chování pro zobrazování vlastního záznamu by zůstalo.

**Comment by motyc** [comment]
@albertoh tak opravdu jde jen o to skrytí, jak jsme se dnes bavili (viz předchozí tři komentáře)

**Comment by albertoh** [comment]
Odstranil jsem katastr z facet a ze seznamu poli pokrocileho vyhledavani

**Comment by motyc** [comment]
Pozor, tady jsme se vůbec nepochopili. Nešlo o to úplně odstranit facetu a danou položku v rožšířeném vyhledávání, ale nevyhledávat přes ně v samostatných nálzech!

**Comment by albertoh** [comment]
Ale to je ten problem: ve vyzledcich muzou byt vedle samostatne nalezy i jine dokumenty.
Ted jsem prejmenoval pole katastr na katastr_pas pro samostatne nalezy, aby se dal "odpojit" od normalniho pole katastr.
Jinak, pri upgrade systemu, to musime redisajnovat.

**Comment by motyc** [comment]
Rozumím, ale každopádně prozatimně vyřešeno, děkuji.
