### ISSUE TITLE
Nefunguje filtrace výběrem v mapě (ani boxem, ani konkrétní bod)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#143]

**Comment by albertoh** [comment]
Opravil jsem vyber konkretniho bodu. Ale pri pokusu vybrat oblast nefunguje. To nefunguje ani v ostrem https://digiarchiv.aiscr.cz/
Zkoumam co se zmenilo v kodu.

**Comment by motyc** [comment]
Na ostrém mi to funguje - viz https://digiarchiv.aiscr.cz/results?pian_ident_cely=P-1313-010104

Možná nějaký problém v datech?

**Comment by motyc** [comment]
Už to vidím - funguje to tak napůl. Heat mapa ano, body ne.

**Comment by albertoh** [comment]
#59

**Comment by albertoh** [comment]
Opravil jsem body. Ale neni to uplne podle meho predstaveni, jak by melo to fungovat. Ale to uz bude vetsi zasah. Delal bych to, az budeme upgradovat project, angular, solr, java libs...
