### ISSUE TITLE
Nefunguje export sam. nálezů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#145]

**Comment by motyc** [comment]
Je nutné zachovat strukturu jako u dokumentu? Bylo by vhodnější využít polí, které samostatné nálezy skutečně obsahují. Takto je to dost nepraktické.

**Comment by albertoh** [comment]
OK. A co kdyz export ma dokumenty obou typu? Asi michat, ne?

**Comment by motyc** [comment]
Pravda, to mne nenapadlo. Máš nějaký návrh, jak to snadno řešit?

**Comment by motyc** [comment]
Uživatelsky nejlepší by bylo, kdyby to třeba otevřelo nikoli jedno okno, ale dvě - zvlášť pro nálezy a zvlášť pro dokumenty.

**Comment by albertoh** [comment]
OK, zkusim to.

**Comment by albertoh** [comment]
Moc to nefunguje. Pri pokusu otevirani vic oknu, prohlizec blokuje to dalsi okno, chrome i mozilla stejne.

Muzu rozdelit ten export na dva. Nejdrive vypsat dokumenty "normalni" a potom samostatne nalezy, s novou hlavicku. Ale vsechno v jednom okne

**Comment by motyc** [comment]
Ano, to jsem měl na mysli jako druhou úspornější variantu :)
