### ISSUE TITLE
Pro sam. nálezy nefunguje časová osa

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#146]

**Comment by albertoh** [comment]
V CSV chybi pole "obdobi_poradi" podle ktereho se hleda v casove ose. Pro dokument ono se najde pres komponenta_dokumentu. Prosim pridat.

**Comment by pbartosova** [comment]
ok, doplnim.

**Comment by motyc** [comment]
K tomu poznámka @albertoh - pořadí je součástí indexovaných heslářů - nešlo by to nějak brát z toho, spíš než upravovat export?

**Comment by albertoh** [comment]
Muzu pri indexaci dohledat pomoci heslare. Jaky mam pouzit obdobi_prvni, obdobi_druha? Predpokladam ze hodnota v csv je brana z jednoho z tech heslaru, je to tak?

**Comment by motyc** [comment]
Ano, je to tak. Je to obdobi_druha.
