### ISSUE TITLE
Relevantní pole sam. nálezů zohlednit v rozšířeném vyhledávání

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#147]
Katastr
Datum
Období
Kategorie předmětu
Druh předmětu
Specifikace předmětu
Okres
Organizace
Popis
Identifikátor
Jméno

**Comment by albertoh** [comment]
Abych mohl to docilit, musim vedet mapovani uvedenych pole do existujicich v csv.
Predpokladam:
Druh předmětu -> druh
Specifikace předmětu -> specifikace
Organizace -> predano_organizace
Jmeno -> nalezce
Datum -> datum_nalezu

Nevidim/nejsem si jist:
Kategorie předmětu, Popis

**Comment by motyc** [comment]
Pravda, kategorie by se musela přidat do exportu nebo načítat z heslářů. Zatím lze nechat stranou.

Popis: lokalizace + poznamka

**Comment by motyc** [comment]
Co mi nefunguje:
Období
Kategorie předmětu - to souvisí asi s tím, že vazba heslářů není nastavená; bylo by to dost práce, asi teď neřešit
Organizace - zde jsou v hesláři nějaké zastaralé hodnoty, mělo by korespondovat s hesláři v CSV

**Comment by albertoh** [comment]
Obdobi v pokrocilem vyhledavani potrebuje zkratku.
Organizace: udaje v datech samostatnych nalezu nejsou v heslari

**Comment by motyc** [comment]
@albertoh výpis pro období opraven, otestovat

**Comment by albertoh** [comment]
Obdobi opraveno.
Reindexoval jsem heslare.

**Comment by motyc** [comment]
Období je ok.

Hesláře jsou bohužel v rozšířeném vyhledávání stále špatně - neodpovídají stavu v test databázi. Není tam na pozadí omylem napojený dev nebo tak něco?

**Comment by albertoh** [comment]
Soubor /var/lib/archeo/amcr/thesauri/organizace.csv na test serveru ma datum 23.5.2018
Asi je zastarale

**Comment by motyc** [comment]
Ok, pak se to asi vyřeší nasazením na produkci, kde to funguje. Patrně na testu jen nejede správně periodický export.
@pbartosova asi by to stálo za opravu, ať nás to nemate.
