### ISSUE TITLE
Dořešit zobrazení v mapě (až bude údaj dostupný z AMČR)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#158]

**Comment by pbartosova** [comment]
Pro archivovane zaznamy by mely byt v exportu k dispozici souradnice v systemu WGS84 - northing a easting a k tomu odpovidajici geometry geom_gml.
Pokud potrebujete nejake upravy, napiste.

**Comment by albertoh** [comment]
Moc tomu nerozumim. Standardne jsme meli souradnice pres pian. Tady vidim nove pridane pole easting a northing v tabulce extra_data. Bude to tak pro vsechny dokumenty nebo jen pro 3D?

**Comment by pbartosova** [comment]
Jedná se o výjimku pro  3D. Ty nebudou mít pian, protože můžou být lokalizovány i mimo ČR. Pro lokalizaci tedy prosím použijte geom_gml resp. easting a northing pole.

**Comment by albertoh** [comment]
Jsou videt tri body. Dva ale jsou mimo CR.
