### ISSUE TITLE
Přestat indexovat dokumenty ve stavu 1 (nerevidováno)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#160]
Mám tušení, že dříve jsme je indexovali, ale vzhledem k jejich využití ve 3D knihovně a celkově posunuté praxi je třeba je přestat indexovat.

**Comment by albertoh** [comment]
Presat indexovat jen dokument, nebo vsechny type (akce, pas...) ?

**Comment by motyc** [comment]
Musíme výhledově tu terminologii nějak ukotvit, jinak se nikdy nedomluvíme :)
Když mluvím na mé straně o dokumentech, myslím skutečně jen to, co je uloženo v datové třídě "dokument". V současnosti jsou to tedy všechny ty dokumenty, co nám tvoří "hlavní" (nikoli podřízené záznamy), s výjimkou samostatných nálezů. Tedy akce, lokality atd. zůstanou nedotčeny.

**Comment by albertoh** [comment]
Odstranil jsem dokument se stavem 1 z indexeru, a take z vyhledavani
