### ISSUE TITLE
Rozdíly v hesláři aktivit

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#161]
Na produkci se liší překlady v hesláři aktivit v rozšířeném vyhledávání (tam je to dobře a aktuální) a ve facetách (špatně).

**Comment by albertoh** [comment]
Preklady pro aktivity bohuzel maji zvlastni zpracovani. A to kvuli rozdilne reprezentaci v ruznych tabulkach: v thesauri pouzivame jako hesla zkratku, ale v komponente mame ho jako nazev pole, nezkraceno, bez diakritiky. V pokrocilem vyhledavani  standardne pouzivame theasuri. To je duvod proc preklady jsou spravne. Pro facety musime to rucne drzet v prekladech, soubory /i18n/cs.json a en.json.
Aktualizoval jsem en.json tak, aby hodnoty odpovidaly thesauri. 
Je to na testu. Tam ale uvidime problem obracene: facet je spravne (bere se z en.json), pokrokile hledani je spatne (bere se z thesauri, a ten je zastarale viz. #147)

**Comment by motyc** [comment]
Díky za vysvětlení. Mě to i napadlo, ale nemohl jsem najít, kde by se to nastavovalo. Asi by to chtělo při plánované aktualizaci nějak sjednotit. Zavírám tedy a dávám to patřičného milestone, ať na to myslíme. Do budoucna se v DB bude řešení pro aktivity stejně měnit, aby se to choval o jako standardní heslář.

**Comment by motyc** [comment]
@albertoh k tomu ještě dotaz - jaký má důvod, že v en.json vedeme i překlady pro areály? Ty by měly být všude standardní...

**Comment by albertoh** [comment]
Je to zastaraly zpusob. Chtelo by to zmenit, a vynechat to.

**Comment by motyc** [comment]
@albertoh A stačí to tedy vymazat z konfiguračních souborů, nebo se musí dělat i něco jiného?

**Comment by albertoh** [comment]
Zkontroluju
