### ISSUE TITLE
Pole "Souřadnice utm:"

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#163]
Tím, jak jsme pro lokalizace začali využívat stávající pole "northing" a "easting" se nám obsah polí objevil v detailu dokumentu. To by nevadilo, nicméně je potřeba:
1) Opravit label na: "Souřadnice (WGS-84)" / "Coordinates (WGS-84)"
2) Formát výpisu upravit na `[northing]N : [easting]E`

**Comment by pbartosova** [comment]
Byl přece úmysl využít existující pole northing a easting. 
Schválně je AMČR i takto exportuje, protože digiarchiv pole geom_gml vůbec nevyužívá. U PIAN využívá centroid_e, centroid_n.

**Comment by motyc** [comment]
Ano, to je úplně v pořádku, jde jen o to, aby se to správně zobrazovalo v Digiarchivu, kde se to teď zobrazuje jako souřadnice UTM, což je chybná informace.
