### ISSUE TITLE
Zobrazují se samostatné nálezy ve špatném stavu (dříve než mají)

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#171]
V Digiarchivu se objevil nález https://digiarchiv.aiscr.cz/id/M-202002934-N00001, který je ale pouze potvrzený (stav 3) a nemá tam co dělat. Samostatné nálezy mají být zobrazeny až ve stavu 4 (archivovaný).

**Comment by albertoh** [comment]
Opraveno.
Konfigurace  SOLRu nebyla spravne deployovana. 
Sice soubor byl tam spravne (s filtrem na stav pro samostatne nalezy), ale nebyl "platny". Je nutne reloadnout core, aby nova konfigurace mela platnost.

**Comment by motyc** [comment]
Děkuji za rychlou opravu.
