### ISSUE TITLE
Umožnit archeologům odpovídající organizace nahlížet na vlastní dokumenty

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#35]
Načítat oprávnění z AMČR tak, aby bylo možno uživateli s oprávněním archeolog zpřístupnit dokumenty vlastní organizace bez ohledu na nastavení přístupnosti.

**Comment by lucka-pavlova** [comment]
Vyžaduje detailní zadání od ARUP. Odhad hodin doplníme po analýze.

**Comment by motyc** [comment]
Budeme řešit výhledově. Prozatím zadáno, abychom nezapomněli,

**Comment by pbartosova** [comment]
Raději later. Určitě se bude jednat o větší zásah. Větší představu pro odhad získáme po vyřešení práv pro nový web.
