### ISSUE TITLE
Upravit listování v seznamu dokumentů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#53]
Do listování v seznamu dokumentů doplnit možnost přejít na konkrétní list, jít na první a jít na poslední.

**Comment by pbartosova** [comment]
Asi užitečná funkcionalita. Snad to tato verze angularu zvládne. Odhad 1-2MD. Měl by dělat vývojář frontendu, který najde nejlepší řešení.

**Comment by albertoh** [comment]
Slo by to delat i v soucasnem disajnu. Neni to velky zasah. Muzeme rozsirit pocet stranek (ted je 5) Nebo pridat editovalne pole pro skok (ale kde? uprostred? nazacatku seznamu?)

**Comment by motyc** [comment]
To je bezva. Dělal bych to nějak podobně, jako toto: 
![image](https://user-images.githubusercontent.com/20186892/81347851-417ab180-90bd-11ea-87d8-7b31cd4cec18.png)
