### ISSUE TITLE
Doplnit obsah k tlačítku nápověda

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#72]
Asi pop-up s informacemi o tom, jak funguje přístupnost a s informacemi k licencování. Na konci může být odkaz sem na Wiki s dokumentací.

**Comment by motyc** [comment]
Nejlepší by bylo řešit stejně jako about a news, tedy samostatným souborem s html, který by se vložil do pop-up okna.

**Comment by pbartosova** [comment]
Raději later, asi si nejedná o stěžejní funkcionalitu, jen nice to have.

**Comment by motyc** [comment]
Ano, ale je to hloupé kvůli uživatelům. Prozatím navrhuji alespoň tedy tlačítko skrýt a vrátíme ho až po doplnění obsahu. Šlo by?

**Comment by motyc** [comment]
Text nápovědy je připraven k nasazení, bylo by tedy dobré realizovat.

**Comment by albertoh** [comment]
Lze editovat text jako novinky a about.
/var/lib/archeo/amcr/texts/help.html
/var/lib/archeo/amcr/texts/help_en.html

Ted je tam text prevzati z wiki

**Comment by motyc** [comment]
Modální okno nápovědy rozšířit na 800px (nyní má 600px).
Automatickou šířku obrázků už jsem vyřešil sám.

**Comment by albertoh** [comment]
Rozsireno, ale na 900, jak to je bootstrapove nastaveni

**Comment by motyc** [comment]
Ok, proč ne, díky.
