### ISSUE TITLE
Stahování originálů

### ISSUE THREAD

**Issue by motyc** [ARUP-CAS/aiscr-digiarchiv#75]
Upravit funkcionalitu tlačítka pro stahování dokumentů tak, aby se zobrazovalo každému, kdo soubor dokumentu může procházet (nyní vidí pouze admin).

Po kliknutí by měl přibýt pop-up s licenčním upozorněním a s preferovanou podobou citace (v hranatých závorkách dynamicky doplnit příslušné hodnoty):
> Tento dokument podléhá licenci [Creative Commons Uveďte původ-Neužívejte komerčně 4.0 Mezinárodní (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/).
> 
> Dokument citujte jako: [autor] [rok]: [typ dokumentu] [ident_cely]. [organizace]. Dostupné z: https://digiarchiv.aiscr.cz/id/[ident_cely].

**Comment by pbartosova** [comment]
Raději later.

**Comment by albertoh** [comment]
Zkontrolovat formatovani textu. Myslim radkovani, a linky

**Comment by motyc** [comment]
Tam, kde to jede, tak je to bezva, něco je ale asi z části rozbité:
1) Při tomto zobrazení: https://digiarchiv-test.aiscr.cz/results?kategorie=pas mi nejde otevřít obrázek u dokumentu C-201900018-N00006 (nic to neudělá).
2) Při otevření přes C-3D-202000174 přes https://digiarchiv-test.aiscr.cz/results?kategorie=ddata3d vše funguje bezva.
3) Při otevření téhož přes https://digiarchiv-test.aiscr.cz/id/C-3D-202000174 se mi pop-up zobrazí pod oknem čtečky. Totéž se děje i jinde, pokud přepnu na angličtinu.
4) Prosím zohledni tam i ty drobné poznámky v #154 (konkrétně body 3 a 4 z https://github.com/ARUP-CAS/aiscr-digiarchiv/issues/154#issuecomment-619871766)
5) "Dokument citujte jako:" prosím dát tučně.

**Comment by motyc** [comment]
Funkčně bez problémů, pouze stejný problém se sam. nálezy, jako v #154.
